### PR TITLE
Fix curator command for recent versions

### PR DESCRIPTION
**Pull request by bsander**
The curator command used here is incompatible with the latest version of curator (3.5.0). It now requires:
- a [subcommand](https://www.elastic.co/guide/en/elasticsearch/client/curator/3.5/delete.html) for selection of indices or snapshots
- a [`timestring`](https://www.elastic.co/guide/en/elasticsearch/client/curator/3.5/timestring.html) option

The only place currently I see curator being used is [here](https://github.com/Enrise/Saltmaster/blame/74bcf5741822c6dc9a972db2bcc88cf911e0dfff/salt/environments/prod/pillars/nodes/logging01.sls#L9-L15). Those lines should not be working correctly with any recent version of curator.
@eXistenZNL since you originally authored those lines, can you verify?

### CODE REVIEW

**Comment by eXistenZNL** [comment]
@bsander doesn't this mean that I have to bump the version of Curator on our logstash environment as well? Otherwise we are stuck with an old version of Currator that is being fed new arguments

**Comment by bsander** [comment]
@eXistenZNL Probably, yeah. That's what I asked you to verify 😉

**Comment by eXistenZNL** [comment]
We are running ES 1.3.9 with Curator 2.0.2 on logging01. Can you advice on upgrading Curator and if needed ES, and to what version? The machine is running Ubuntu 14.04 LTS.

**Comment by bsander** [comment]
I'm no expert on curator myself, but according to the docs, versions 3.x support running against elasticsearch 1.x: https://github.com/elastic/curator/tree/3.5#versioning

Upgrading is described here: https://www.elastic.co/guide/en/elasticsearch/client/curator/current/upgrading.html

Apparently an upcoming version 4 of curator will only support elasticsearch 2.x and up, so maybe we should explicitly specify a curator version in this formula as well? https://github.com/elastic/curator/tree/master#versioning

**Comment by eXistenZNL** [comment]
@bsander currently don't have the time to go update our logging01 environment so not sure that to do now. Can't really merge without breaking stuff for us afaics. @sabinejansen please advice, since my time is booked :)

**Comment by bsander** [comment]
Yay for shared state. I imported the changes to a local state in the Saltmaster so feel free to defer this one as long as you like.

**Comment by eXistenZNL** [comment]
We can all enjoy a shared state as long as it is made configurable :) Will be deferring until furter notice, @gdegraaf and @sabinejansen will plan this in in the near future.

**Comment by eXistenZNL** [comment]
@bsander merged, you can clean up your custom implementation in favour of this global one :)

**Comment by bsander** [comment]
🎉

**Pull request merged**
