### PR TITLE
Hold the package if a version pin is set to prevent unwanted upgrades

### PR DESCRIPTION
**Pull request by syphernl**

### CODE REVIEW

**Comment by syphernl** [comment]
FYI @Enrise/sashimi @Enrise/matchminds: This will prevent the automatic updates for certain servers to keep trying to upgrade the version to latest.

**Comment by edwardsmit** [comment]
👍🏻 We had already added this step in our role-definition. Does this also support upgrades? So when we bump the version the hold will be lifted temporarily?

**Comment by syphernl** [comment]
If you change the version in the pillar configuration it should pin to that new version, allowing you to upgrade it. 

But right now this is causing some issues for servers that aren't explicitly holding the package resulting in daily upgrade-downgrade cycles when we run upgrades for servers that are configured to allow unattended upgrades.

**Comment by edwardsmit** [comment]
Great. And yes, that's exactly why we added a call to `apt-mark hold elastic search`

**Pull request merged**
